const NavActionTypes = {
    GET_NAV_ITEM : 'GET_NAV_ITEM',
    GET_NAV_ITEM_CHILD : 'GET_NAV_ITEM_CHILD',
    SET_NAV_CLICKED : 'SET_NAV_CLICKED',
    SET_NAV_OPEN: 'SET_NAV_OPEN',
    TOGGLE_NAV_ITEM_HIDDEN : 'TOGGLE_NAV_ITEM_HIDDEN'
}

export default NavActionTypes;